In [6]:
1+1

2

In [12]:
import numpy as np
array = np.array([[1,2,3] , [4,5,6] ,[7,8,9]])
print(array)
type(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

**Syntax and Semantics in Python**

In [10]:
# Basic Syntax
#Case Senstivity -- python is Case Sensitive

a = '''Hello Myself Kiriti Aajad 
       This is python basics file '''

print(a)
 

Hello Myself Kiriti Aajad 
       This is pytho basics file 
