## NumPy ##
NumPy is a fundamental package for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.

## Key Features ##
N-dimensional Arrays: Efficiently handle large datasets with multi-dimensional arrays.
Mathematical Functions: A wide range of mathematical operations, including linear algebra, Fourier transforms, and random number generation.
Performance: Optimized for performance with operations implemented in C.
Integration: Seamlessly integrates with other scientific libraries like SciPy, pandas, and matplotlib.


In [14]:
import numpy as np # type: ignore

## create arrays using numpy 
# create a 1D array 
arr1 = np.array([1 ,2,3,4,5,6,7,8,9,10])
print(type(arr1))
print(arr1)
print(arr1.shape)

<class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10]
(10,)


In [15]:
arr2 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9 ]])
print(type(arr2))
print(arr2)
print(arr2.shape)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [16]:
one = np.ones((3,2))
print(one)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [17]:
zero = np.zeros((2,9))
print(zero)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [18]:
# Identity Matrix
ident  = np.identity(3)
print(ident)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
matrix = np.array2string(arr2)
print(matrix)
print(type(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'str'>


In [20]:
# Numpy Vectorized operation 
import numpy as np
arr1 = np.array((1,2,3,4,5,6,7,8,9))
arr2 = np.array((9,8,7,6,5,4,3,2,1))

# Element wise subtraction 
print(arr1+ arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 /arr2)

[10 10 10 10 10 10 10 10 10]
[-8 -6 -4 -2  0  2  4  6  8]
[ 9 16 21 24 25 24 21 16  9]
[0.11111111 0.25       0.42857143 0.66666667 1.         1.5
 2.33333333 4.         9.        ]


In [21]:
print(np.sin(arr1))
print(np.exp(arr2))
print(np.log(arr1))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]
[8.10308393e+03 2.98095799e+03 1.09663316e+03 4.03428793e+02
 1.48413159e+02 5.45981500e+01 2.00855369e+01 7.38905610e+00
 2.71828183e+00]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [22]:
# Array slicing and Indexing 

arr3 = np.array([[1,2,3,4,5],
                 [6,7,8,9,0] ,
                 [1,2,3,4,5]])

print(arr3)

[[1 2 3 4 5]
 [6 7 8 9 0]
 [1 2 3 4 5]]


In [23]:
print(arr1)
print(arr2)
output = np.dot(arr2 , arr1)
print(output)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
165


In [24]:
matrix1 = np.array([[1,2,3] ,
                   [1,2,3]])

matrix2 = np.array([[1,9,5] ,
                    [1,2,3]])
print(matrix1)
print(matrix2)
print(matrix2.T)
output = np.dot(matrix1 , matrix2.T)

print(output)

[[1 2 3]
 [1 2 3]]
[[1 9 5]
 [1 2 3]]
[[1 1]
 [9 2]
 [5 3]]
[[34 14]
 [34 14]]


In [25]:
# Statistical Concepts
data  = np.array([1,2,3,4,5,6,7,8,9])
mean = np.mean(data)
std_dev = np.std(data)
normalized_data = (data -mean) /std_dev
variance = np.var(data)
print(variance)
print(mean)
print(std_dev)
print(normalized_data)
print(np.mean(normalized_data))

6.666666666666667
5.0
2.581988897471611
[-1.54919334 -1.161895   -0.77459667 -0.38729833  0.          0.38729833
  0.77459667  1.161895    1.54919334]
0.0


In [26]:
# Logical Operations
data[data>5]

array([6, 7, 8, 9])